version: "3.4"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - default
    ports:
      - "5434:5432"
    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_USER=demo_user"
      - "POSTGRES_PASSWORD=demo_pass"

  ui:
    image: adminer
    restart: always
    networks:
      - default
    ports:
      - "8082:8080"
    depends_on:
      - db
